"""new fields in user model

Revision ID: 68efab2597d2
Revises: e01c4c1aa156
Create Date: 2021-10-06 10:08:31.028141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68efab2597d2'
down_revision = 'e01c4c1aa156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
